### ISSUE TITLE
BUG-Missing link to taipy.gui.notify

### ISSUE THREAD

**Issue by bengaid** [Avaiga/taipy-doc#1046]
Missing link : https://docs.taipy.io/en/develop/manuals/reference/taipy.gui.notify

**Comment by FabienLelaquais** [comment]
Well... this link was moved with a refactoring of the whole doc.
Try https://docs.taipy.io/en/develop/manuals/refmans/reference/taipy.gui.notify/

If this works, @bengaid, do you agree this issue should be dropped?

**Comment by jrobinAV** [comment]
The URL has changed to https://docs.taipy.io/en/develop/manuals/refmans/reference/taipy.gui.notify
