### ISSUE TITLE
Better expose the code samples linked from the User Manual

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-doc#1074]
**Description**

In the visual element documentation pages, just after the title of specific use cases, there sometimes is a line that says:
"You can download the entire source code used in this section from the GitHub repository."

That provides a link to the taipy repository when the entire code can be looked at and downloaded.
However, this line seems to not be visible enough.

**Expected change**

Get users to easier spot this line so they can download complete code fragments.

**Comment by AlexandreSajus** [comment]
- One way would be to add the complete code at the bottom of the page.

- Another way would be to make a big visible button like these:

![image](https://github.com/user-attachments/assets/506ff420-b4b2-4401-825e-5a7a99a3ff17)

- Another way would be to include all code snippets in the page. This way the user can copy paste each code snippet within his IDE and have the complete code this way.

**Comment by FabienLelaquais** [comment]
I want to page to focus on the important stuff: the element definition.
The rest is grammar.
