### ISSUE TITLE
[DOCS] <single_client configuration parameter to False - ..>

### ISSUE THREAD

**Issue by smahable** [Avaiga/taipy-doc#1139]
### Issue Description

https://docs.taipy.io/en/release-3.1/manuals/gui/callbacks/

(note that setting the single_client configuration parameter to False - as explained in the [Configuration](https://docs.taipy.io/en/release-3.1/manuals/gui/configuration/#configuring-the-gui-instance) section - prevents multiple users from connecting to your application simultaneously, but you still rely on the [State](https://docs.taipy.io/en/release-3.1/manuals/reference/taipy.gui.State) object to access the application variables that are represented in your user interfaces)."

I think you meant setting it to True ?

### Screenshots or Examples (if applicable)

n/a

### Proposed Solution (optional)

change False to True ?

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
Hi, I am not sure to understand this issue.

What is wrong with this documentation?

>single_client (bool, default: False): set to True if only a single client can connect. False, which is the default value, indicates that multiple clients can connect to the server.
Note that this setting is forced to True when running in a Notebook context.

**Comment by smahable** [comment]
https://docs.taipy.io/en/release-3.1/manuals/gui/callbacks/

Its not big deal but to just confirm:

single_client=True  # only single client can connect
single_client=False # multiple clients can connect

If you see the wording I pasted from the doc, the wording is confusing

thanks

**Comment by FlorianJacta** [comment]
Oh I get it. This is from our docs your text:

> note that setting the single_client configuration parameter to False - as explained in the [Configuration](https://docs.taipy.io/en/release-3.1/manuals/gui/configuration/#configuring-the-gui-instance) section - prevents multiple users from connecting to your application simultaneously, but you still rely on the [State](https://docs.taipy.io/en/release-3.1/manuals/reference/taipy.gui.State) object to access the application variables that are represented in your user interfaces 


which is false.

Thank you for bringing this to us!

**Comment by yashpal2104** [comment]
Is this issue resolved or can I fix this and make a pull request

**Comment by yashpal2104** [comment]
This issue is resolved I have screenshoted it but still in the official documentation it is not reflected 
![Screenshot 2024-09-26 211311](https://github.com/user-attachments/assets/c5f409a2-07c9-4249-9b65-14f136b66e34)
![Screenshot 2024-09-26 211645](https://github.com/user-attachments/assets/a8a8741e-c882-45bc-92d4-f8644b0f09a6)

**Comment by FlorianJacta** [comment]
This is fixed in the develop version of Taipy https://docs.taipy.io/en/develop/userman/gui/callbacks/

This documentation will be live very soon. We are planning our 4.0 release!

Thank you for your contribution again.

**Comment by yashpal2104** [comment]
Glad to help!
