### ISSUE TITLE
BUG-Installation

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy-doc#1142]
**Bug description**
I was trying to run the project but I got an error on the installation guide step 2. 

**Screenshots**
![Screenshot from 2024-10-01 06-53-14](https://github.com/user-attachments/assets/7fa3ec15-87bd-4206-9c75-b4b4fba49b26)

**Comment by FabienLelaquais** [comment]
Thank you for reporting this problem @Satoshi-Sh.
That is due to a bug in the setup process relying on unaccessible repositories.
I'll be working on this one.
