### ISSUE TITLE
Feature Request: AgGrid Integration for Tabular Data Control

### ISSUE THREAD

**Issue by sumanth-dhanya** [Avaiga/taipy-doc#1150]
Description: Incorporating support for AgGrid as a Tabular Data Control within Avaiga would provide enhanced functionality and flexibility for users. AgGrid is a powerful grid library that supports a wide range of features such as sorting, filtering, pagination, and customizable styling. This integration can significantly improve the user experience for handling and visualizing tabular data.

Currently, other libraries such as Reflex and Streamlit have already implemented AgGrid components:

Reflex: [AgGrid in Reflex](https://reflex.dev/blog/2024-09-25-using-ag-grid-in-reflex)
Streamlit: [Custom Components Documentation](https://docs.streamlit.io/develop/concepts/custom-components)
Expected Change: Introduce AgGrid support as a component within Avaiga, allowing users to utilize its advanced tabular data features. This enhancement would align Avaiga with other modern data visualization frameworks, making it more competitive and user-friendly for data-driven applications.

Benefits:

Improved data visualization with sorting, filtering, and editing capabilities.
Enhanced customization options for styling and formatting tabular data.
Consistency with other libraries that have adopted AgGrid, making it easier for users transitioning between platforms.
Contributions: I am open to contributing to this feature request and would be happy to collaborate with the team or other contributors to make this integration successful.

**Comment by FlorianJacta** [comment]
Taipy already has an issue about AgGrid here: https://github.com/Avaiga/taipy/issues/451

I am closing this as a duplicate. We'll create a doc issue when necessary
