### ISSUE TITLE
[DOCS] Reference manual pages about visual elements should clearly point to their doc

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#1152]
### Issue Description

We got a support ticket about documentation. Someone looked on Google for Taipy table doc and stumbled onto this page and complained that there was no information on the page: https://docs.taipy.io/en/release-3.0/manuals/reference/taipy.gui.builder.table/

This is because it is a reference manual page and not the page he was looking for. The page he was looking for is this one: https://docs.taipy.io/en/latest/manuals/gui/viselements/table/#__tabbed_1_3

There should be a big button on ref manual pages about visual elements that redirect to the visual element documentation.

Refers to Avaiga/taipy#1611

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by codermal7** [comment]
Hi, can i work on this? @AlexandreSajus

**Comment by AlexandreSajus** [comment]
Sure! Just so I'm clear: I want all the visual elements pages like these: https://docs.taipy.io/en/release-3.0/manuals/reference/taipy.gui.builder.table/

To point to their more useful counterparts like these: https://docs.taipy.io/en/latest/manuals/gui/viselements/table/#__tabbed_1_3

With a big visible button, something like what we did here:
![image](https://github.com/user-attachments/assets/4475841a-f312-4880-88d4-9f5221063c4f)

The repo that contains our docs is here: https://github.com/Avaiga/taipy-doc

Assigned!

**Comment by FabienLelaquais** [comment]
@AlexandreSajus 
Would this please you?
![image](https://github.com/user-attachments/assets/421a3421-a5f3-4099-975c-d26a7001096f)

**Comment by FabienLelaquais** [comment]
@codermal7 @AlexandreSajus 
Sorry I didn't spot this was assigned: this issue was not properly moved to the Contribution slot, and not even planned for the current sprint.
So I did the job because it was raining outside...

If @AlexandreSajus likes this proposal, we're done with that.

**Comment by AlexandreSajus** [comment]
This pleases me.
