### ISSUE TITLE
Add documentation for the new aws S3 Object capabilities.

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#1166]
In taipy doc [page](https://docs.taipy.io/en/develop/userman/scenario_features/data-integration/data-node-config/#amazon-web-service-s3-object) must be updated regarding the new capability of the `S3ObjectDataNode` implemented in the PR https://github.com/Avaiga/taipy/pull/1868

The file is located at `docs/userman/scenario_features/data-integration/data-node-config.md`

**Comment by jrobinAV** [comment]
@AdeshGhadage FYI

**Comment by AdeshGhadage** [comment]
@jrobinAV can you assign me this issue?
