### ISSUE TITLE
BUG-404 Error on "Get it on GitHub" Link for Churn Classification Demo

### ISSUE THREAD

**Issue by abhirajadhikary06** [Avaiga/taipy-doc#1173]
**Bug description**
When clicking the "Get it on GitHub" button for the Churn Classification Demo, the link redirects to a 404 "Not Found" page, indicating that the GitHub repository does not exist or the link is broken. [!Churn Classification](https://docs.taipy.io/en/release-3.0/knowledge_base/demos/churn_classification/)

Steps to Reproduce:

Navigate to the Churn Classification Demo page.
Click on the "Get it on GitHub" button.
The page redirects to a 404 error on GitHub.
Expected Behavior:
The link should redirect to the corresponding GitHub repository where the code for the Churn Classification demo is hosted.

**Expected change**
When clicking "Get it on Github" for Churn Classification -- this Demo it open 404 not found. Which clearly explains that this repos is not there on github.

**Screenshots**
![Churn Classification](https://github.com/user-attachments/assets/b68696eb-70a3-40ef-9c8f-0adcaa97b379)

**The screenshot provided above points to the issue shown below**
![Error-page](https://github.com/user-attachments/assets/17048b9d-d858-4409-b9f8-9ecfce8572eb)

**I propose creating a new repository dedicated to churn classification. Once established, we should include its link in the relevant documentation. @jrobinAV I'd like to be assigned the issue of setting up this repository and ensuring its integration with the documentation. It would be grate if this issue is assigned a label of 'hacktoberfest-100💎'**

**Comment by FlorianJacta** [comment]
You are on an old documentation for Taipy. Go to the latest documentation of Taipy. This repo has been closed-source. The "Error 404" is normal. The button you clicked on doesn't exist anymore in the new doc.

How did you find this old documentation?

**Comment by abhirajadhikary06** [comment]
https://github.com/avaiga/taipy ---> Scroll down to 'Applications' ---> Select any project
**Hope you will get to see it there**
