### ISSUE TITLE
Add to Getting Started taipy create CLI

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#1214]
**Description**
Add to the Getting Started page of the documentation a part about the CLI and particularly the `taipy create` command line that allows to create a multi-page app easily.

**Expected change**
This section should be at the end of the Getting Started.

**Comment by Satoshi-Sh** [comment]
![Screenshot from 2024-11-27 17-28-53](https://github.com/user-attachments/assets/e8fa17c7-f12a-4c44-83cd-df861a104f20)

Do I just need to add this info to the getstarted page?

**Comment by FlorianJacta** [comment]
Yes but shorter. One sentence or two to explain that you can create directly a multi-page application with templates and then `taipy create`. @Satoshi-Sh Do you want to be assigned?

**Comment by Satoshi-Sh** [comment]
Sure. I can take this issue.

**Comment by FlorianJacta** [comment]
Thank you @Satoshi-Sh !
