### ISSUE TITLE
Pyodbc installation on Linux

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy-doc#162]
To be able to use SQL Server Database as Data Node, users should install OBDC.
We should provide documentation.

CFM Dockerfile as example:

FROM python:3.10
EXPOSE 5025/tcp
WORKDIR /cfmv2
RUN apt update -y  &&  apt upgrade -y && apt-get update
RUN apt-get install -y --no-install-recommends \
    unixodbc-dev \
    unixodbc \
    libpq-dev

# Add SQL Server ODBC Driver 18 for Ubuntu 18.04
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql18
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

RUN apt-get update -y && \
    apt-get install -y python3.pip python3-dev
COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .
#ENTRYPOINT /bin/bash
CMD ["python3", "main.py"]

**Comment by joaoandre-avaiga** [comment]
I think maybe we should change from ubuntu 18.04 to 22.04 which is the new LTS version
