### ISSUE TITLE
Show cacheable parameter in the doc of DataNodeConfig and wrong type of **properties

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#196]
- *cacheable* parameter is not shown in the parameters of the DataNodeConfig. It is hidden by **properties. It should be documented somewhere.
- Moreover, **properties seems to have the wrong type (taipy.core.Scope) on this [page](https://docs.taipy.io/en/latest/manuals/reference/taipy.core.data.data_node.DataNodeConfig/).

**Comment by toan-quach** [comment]
@FlorianJacta 
We (me and JR) have decided to move the `cacheable` parameter out of the `**properties`. This should help improve user experience through code-suggestion and make documentation a lot easier and cleaner as well! Let me know what you think :D

**Comment by FlorianJacta** [comment]
Very good idea. I think we should do the same for any important parameters that are in the **properties if any
