### ISSUE TITLE
Documentation - Transform credits page into an "About" page like in the MUI website

### ISSUE THREAD

**Issue by AAstridVH** [Avaiga/taipy-doc#2]
**What would that feature address**
Have a more general page that highlights both Avaiga and the contributors, as well as the community. This page will also link to the Taipy site and the Avaiga site.

***Description of the ideal solution***
Provide the following sections:

- Quick presentation of Avaiga and Taipy and highlighting customers (if possible),
- Presentation of the objectives,
- Team,
- Community and contributors if possible,
- Brief reminder of how to become a contributor,
- Small CTA to encourage to clone the project and to launch.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by florian-vuillemot** [comment]
Move https://docs.taipy.io/credits/development_lead/ to the website
Email: dev@taipy.io
Doc credit => website credit or remove ?

**Comment by florian-vuillemot** [comment]
@FabienLelaquais can you please have a look at this card ?

**Comment by AAstridVH** [comment]
Replace with a message like "Find out more on the Taipy Website". It is important to mention that the link redirects to a website about Taipy (not Avaiga).

![Capture d’écran 2022-05-12 à 09 10 46](https://user-images.githubusercontent.com/96520448/168012672-498d87ec-82b3-4112-aef2-fc7aa4726588.png)
