### ISSUE TITLE
BUG-We lose the highlight of the section in the doc

### ISSUE THREAD

**Issue by vhfgosselin** [Avaiga/taipy-doc#235]
**Bug description**
The section is not highlighted at the top of the page when I click on an item description

**Expected change**
The Reference Manual or User Manual should get highlighted.

**Screenshots**
This is good, the section (here _User Manual_) is highlighted at the top 
![image](https://user-images.githubusercontent.com/20767690/195199830-092414a1-4e67-48c8-9152-bf4821937860.png)

This is bad: the section is not highlighted anymore.
![image](https://user-images.githubusercontent.com/20767690/195200052-c0327274-debd-43ed-8be6-5fc74085f8da.png)

ANother Example:
Good: I am in the User Manual which gets highlighted 
![image](https://user-images.githubusercontent.com/20767690/195202819-8f4eee16-838e-4b1a-a457-7278a751b959.png)

But when I click on the link "Getting Started document", no section gets highlighted anymore. Here the _Getting started_ should get highlighted.
![image](https://user-images.githubusercontent.com/20767690/195203103-4340da9b-2b5c-406f-b875-5dfeda9d0c86.png)

**Comment by jrobinAV** [comment]
Can't reproduce in taipy 3.0
