### ISSUE TITLE
Improve documentation for Gantt charts

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-doc#245]
**Description**
The Gantt chart documentation in `docs/manuals/gui/viselements/charts/gantt.md` is difficult to understand. Notably:

1. Definition of the task duration is confusing.
2. The resolution of the image (`docs/manuals/gui/viselements/charts/ganttlike1.png`) is too low to be readable. This made it hard for me to reverse engineer and figure out what the code was doing.

**Expected change**

1. Improve the description for defining a Gantt chart. Perhaps have each line begin with the name of the "parameter". Be clear with how task durations are defined (as the offset from 1970-01-01).
2. Increase the resolution of the attached image.

**Comment by FabienLelaquais** [comment]
I hope things are clearer now in the User Manual/GUI/Visual Elements/Charts/Gantt section...
