### ISSUE TITLE
BUG- Wrong property in configure_data_node() function

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#255]
**Bug description**
Wrong property name in the [User Manual/Taipy Core/Configuration/Tasks configs ](https://docs.taipy.io/en/latest/manuals/core/config/task-config/)
`input_data_node_cfg = Config.configure_data_node("input", default_value=21)`

**Expected change**
Change it to:
`input_data_node_cfg = Config.configure_data_node("input", default_data=21)`

**Comment by jrobinAV** [comment]
Must be implemented on versions 1.1, 2.0, and 2.1 !
