### ISSUE TITLE
Add doc examples for heatmap charts

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#260]
**Description**
Heatmap charts are accessible through the Taipy Gui API. We should provide examples of this type of charts.

**Expected change**
There should be a new charts sub-section dedicated to heatmap charts.

**Comment by haotran-avaiga** [comment]
It is the same with this issue https://github.com/Avaiga/taipy-doc/issues/286 right?

**Comment by FabienLelaquais** [comment]
Covered by #286 and #292.
