### ISSUE TITLE
Add documentation for Parquet DataNode

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#276]
Add documentation on :
- How to configure Parquet data node
add a new section in [data node configuration](https://docs.taipy.io/en/develop/manuals/core/config/data-node-config/)
- How to use Parquet data nodes
Add a new section in [data node management](https://docs.taipy.io/en/develop/manuals/core/entities/data-node-mgt/#read-write-a-data-node)

**Comment by arcanaxion** [comment]
Working on this! @trgiangdo
