### ISSUE TITLE
Documentation - Contributing - Inform potential contributors about used tools

### ISSUE THREAD

**Issue by AAstridVH** [Avaiga/taipy-doc#3]
**Description**
For some types of contributions, specify, if relevant, which technology(ies) Taipy uses

As an example, in order to expand the documentation, explain that the present support is made using MKDocs and propose a link to know more about its usage.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by florian-vuillemot** [comment]
https://docs.taipy.io/contributing/contributing/
