### ISSUE TITLE
General updates to the data node management and configuration pages

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-doc#321]
**Description**
While adding documentation for Parquet to the DN management and configuration pages (#298), some other improvements may be made to these pages.

**Expected change**
- The phrasing _"described in the previous section [Data node configuration](data-node-config.md)"_ in data-node-config.md should be reworded. Consistency across all data nodes (currently I notice Parquet and JSON to be using updated phrasing). 
- Remove the `data_node.write({"date": "12/24/2018", "nb_sales": 1550})` example for CSVDataNode. It would currently throw an error from the pd.DataFrame constructor. The argument needs to be wrapped in a list.
- Other general phrasing/typo changes.

**Comment by jrobinAV** [comment]
Hello Zac, 
I saw a draft PR on that topic. Are you working on this ?

Thx,

**Comment by arcanaxion** [comment]
Hi @jrobinAV. Sorry, it shouldn't be draft - it's ready for review

**Comment by jrobinAV** [comment]
Oh, even better!

Thx!
