### ISSUE TITLE
Document the return type and value of the submit methods 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#393]
**Description**

The return of the *taipy.core.submit* function needs to be documented in the Ref man and the User Manual.

**Comment by toan-quach** [comment]
@FlorianJacta @jrobinAV 
- Regarding the User Manual, I'm thinking the appropriate place for documenting the returning type of the submit methods would be at this page https://docs.taipy.io/en/latest/manuals/core/entities/scheduling-and-job-execution/#submit-a-scenario-pipeline-or-task at line "To execute a scenario, you need to call the submit() method:" -> something similar to this "To execute a scenario, you need to call the submit() method, which will return a dictionary of pipeline ids and newly created list of Jobs:" (we can document further that the return type can differ depends on if we're submitting a scenario, a pipeline or a task.
- As for the Ref Manual, I have added a line to define the return type of the submit function in core (src/taipy/core/taipy.py): "If a `Scenario^` is submitted, it will return a dictionary of the pipelines' id as the key and the list of created jobs as value. If a `Pipeline^` is submitted, it will return a list of created `Job^`. And if  a `Task^` is submitted, it will return a created `Job^`." I'll also add similar lines to the `submit()` method in scenario.py, pipeline.py and task.py and I think that's about it. 
Let me know if you think there's anything missing or if I got it wrong.

**Comment by FlorianJacta** [comment]
It seems great!

**Comment by jrobinAV** [comment]
Good for me.
