### ISSUE TITLE
Core notification documentation

### ISSUE THREAD

**Issue by toan-quach** [Avaiga/taipy-doc#416]
**Description**
Add documentation for the new notification mechanism in core. 
Follows ticket [taipy-#405](https://github.com/Avaiga/taipy/issues/405).

**Expected change**
- [x] Ref manual
- [ ] User manual - The user man should contain an example showing use case of ticket #1030

**Comment by jrobinAV** [comment]
Blocked by [doc-#709](https://github.com/Avaiga/taipy-doc/issues/709).

**Comment by jrobinAV** [comment]
Here is a proposed structure

## Structure

This is under the SDM page:

1. Listening SDM events => events/index.md
2. Understanding topics => events/understanding-topics.md
3. Events description => events/events-descriptions.md
4. Advanced Examples => events/examples.md

## 1. Listening SDM events

1. What is a topic (high-level definition) - Cross ref to page 2 for more details
2. What is an event (high-level definition) - Cross ref to page 3 for more details
3. Why register for topics with practical use cases
4. How to overview - Should explain we need to register to a topic and implement a consumer
5. Simple but complete example
 
## 2. Understanding Topics

1. What is a topic
2. How to register for one topic
3. Examples: Code snippets and explanations.

## 3. Events List

- What is an event
- The exhaustive list of events. Should it be categorized by entity type? (or maybe by operation???)
    For each event:
        - Brief description of each event.
        - Attributes associated with each event.
- How to consume and process events
    Explanation of event consumption process.
    Code examples for processing and handling events.

## 4. Examples: 
A few complete examples with detailed explanation, step-by-step guide and code sample
- Consuming Scenario creation events and notifying the User in the user interface
- Consuming an output Data node edition and call a fake rest API with the new data and the comment attached to the last edition
- Consuming Job failure events and send an email to an admin user
- etc.

**Comment by FlorianJacta** [comment]
Seems great!

**Comment by jrobinAV** [comment]
The PR [1047](https://github.com/Avaiga/taipy-doc/pull/1047) is in progress. 
It remains a couple of things (the example page, the mkdocs.yml_template update, etc.) but should be reviewed and approved soon.

**Comment by jrobinAV** [comment]
The first PR has been merged. However, the example page should be improved.
Each example should have an introductory paragraph explaining the interest, motivation, and purpose of the use case.

**Comment by jrobinAV** [comment]
Can it be moved to done?
