### ISSUE TITLE
Documentation on using Taipy Version system with other Revision control software (Git, DVC, ...)

### ISSUE THREAD

**Issue by trgiangdo** [Avaiga/taipy-doc#418]
Add example on how to:
- Store a version code with Git. Revert the code (Config, functions) to a specific version using git and Taipy.
- Use DVC to store and manage data version with Taipy.

**Comment by jrobinAV** [comment]
Hi Giang, 
I believe these are 2 separate documentation set. One with Git, one with DVC. We could also add MLFlow tracking. No?

Anyway, you seem to have something precise in mind. If so, can you prepare a structure of the documentation you have in mind, so we better understand the purpose and the expected result.

**Comment by trgiangdo** [comment]
I take the inspiration from DVC doc: https://dvc.org/doc/start/data-management/data-versioning

In their doc, they demonstrate how to use git along side dvc to control data versions.

I think we can do something similar, but I doesn't have a clear structure yet.
