### ISSUE TITLE
Change Pipeline/PipelineConfig documentation 

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#508]
- [ ] Replace Pipeline by sequence
- [ ] Document the removal of taipy.create_pipeline()
- [ ] Document the rename of Config.configure_scenario_from_tasks() to Config.configure_scenario() to replace the old one.

**Comment by trgiangdo** [comment]
TODO:
- [ ] Document the removal of `taipy.create_pipeline()`
- [ ] Document the rename of `Config.configure_scenario_from_tasks()` to `Config.configure_scenario()` to replace the old one.
