### ISSUE TITLE
Complete Getting Started 

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#564]
Remove the TODO and replace it with a description of the Gui part of the GS.

https://docs.taipy.io/en/develop/getting_started/#graphical-interface

**Comment by FlorianJacta** [comment]
- [x]  Create the content of the Getting Started
- [ ]   Create the illustration for the Getting Started @marisogo

**Comment by jrobinAV** [comment]
@marisogo any news on the topic?
