### ISSUE TITLE
Add a style for doc videos

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#616]
Create a style "tp-video" and apply it to all taipy videos in the documentation.

**Comment by jrobinAV** [comment]
@FlorianJacta Is this issue still relevant? I believe you did something about videos recently. Do we have a factorized styling for videos in the taipy documentation?

**Comment by FlorianJacta** [comment]
I didn't do anything for videos, just images

**Comment by Satoshi-Sh** [comment]
Hi, I would like to take this issue. 

~Do I just need to add class="tp-video" to all the video elements?~
~No, need to style in CSS.~

**Comment by trgiangdo** [comment]
Hello @Satoshi-Sh, next time please comment on the issue that you want to work on, then wait for being assigned first before actually engaging and creating a PR, so we can keep track of what is being worked on.

I will assign this issue to you now. Thank you.

**Comment by Satoshi-Sh** [comment]
Thanks for your assistance, @trgiangdo . I will wait to get assigned next time.
