### ISSUE TITLE
Chart page property table should contain all relevant properties

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#657]
We have been discussing how to make complex charts more accessible. We have been looking for a possible fix with Vincent and Florian.

When writing a complex chart, the main issue is finding the relevant Plotly js properties. The reason why these properties are hard to find is that the link for the Plotly doc is only at the bottom of the [chart page](https://docs.taipy.io/en/develop/manuals/gui/viselements/chart/) and the property table is too crowded
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/ce34f1cc-b582-4a54-afec-448a93f7c850)

Generally the user does not scroll that far and can not find what he needs.

The fix we propose is to dispatch each relevant property into the pages of each specific chart. For example the [line chart page](https://docs.taipy.io/en/develop/manuals/gui/viselements/charts/line/) should have the layout property in its table:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/93b48ded-4255-4ddc-88b3-131777346179)

**Comment by FabienLelaquais** [comment]
An idea could be to add a collapsible section that would show properties that are applicable, and not the ones that are *not* irrelevant.

**Comment by jrobinAV** [comment]
Done, waiting for feedback.
