### ISSUE TITLE
Add post processing to generate index pages in the Knowledge_base chapter

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#671]
- [ ] Add meta data in each page:
    - Maintainer
    - keywords
    - description
    - title
    - icon image
- [ ] postprocess kb/index.md
- [ ] postprocess kb/tutorials/index.md 
- [ ] postprocess kb/demos/index.md 
- [ ] postprocess kb/tips/index.md

**Comment by jrobinAV** [comment]
@FlorianJacta 
This ticket can be close, right?

**Comment by FlorianJacta** [comment]
Yes
