### ISSUE TITLE
Ensure search engines are pointing to the right page version (latest)

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#672]
Clue:
From the ReadTheDocs site: [How can I avoid search results having a deprecated version of my docs?](https://docs.readthedocs.io/en/stable/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs).

**Comment by AlexandreSajus** [comment]
Here is an example:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/5ce5a19f-c8ca-4e34-8983-507056098b3b)

**Comment by AlexandreSajus** [comment]
A workaround for this would be creating a big red warning box at the top of the page warning the user that he is not on the latest version of the docs. Streamlit does this:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/11695347-ad5f-4b82-bf97-ab2d4e7a9a8c)
