### ISSUE TITLE
BUG-Wrong cross-refs to Reference Manual

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-doc#678]
**Bug description**

Some API elements have the same name although located in different modules.
An example would be `taipy.gui.Page` and `taipy.gui.builder.Page`. When the element name is the only provided information (in a link looking like \`TheElement\^\`), the doc generator postprocessor tries to find the element among all documented ones.
As of today, this search may pick a wrong element.

**Expected change**
There should be a way to specify which package the element should be searched for.

We need to extend the cross-def syntax to allow for specifying as little packages as possible.
In our example, that would be \`(builder.)Page\` to specify which we want.

**Comment by jrobinAV** [comment]
As a workaround, can we use the [`taipy.gui.Page`](../manuals/ref/taipy/gui/page.md) syntax?

**Comment by FabienLelaquais** [comment]
Yes but then it's really not nice in the text flow.
