### ISSUE TITLE
Create a FAQ section

### ISSUE THREAD

**Issue by AAstridVH** [Avaiga/taipy-doc#7]
**What would that feature address**
It is no possible for the users to find quick solutions to frequently met issues.

***Description of the ideal solution***
Create a FAQ with a troubleshooting section.

***Caveats***
This FAQ section should share solid bounds with the documentation and be regularly updated with users feedbacks.

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by florian-vuillemot** [comment]
@FlorianJacta can provide some.
Put in Website.

**Comment by jrobinAV** [comment]
1 - When running a Taipy GUI application, why do we have a warning : 
```
 * Server starting on http://127.0.0.1:5000
 * Serving Flask app 'Taipy' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Server starting on http://127.0.0.1:5000
```
It is normal. Taipy wants to make it easy to run the GUI when you are developing your app. The easiest way is to use a development server (provided by Flask). When it comes to deploy the application on a production environment, please refer to the doc to use a production server.

**Comment by AAstridVH** [comment]
https://www.taipy.io/faq/

**Comment by florian-vuillemot** [comment]
- Plotly usage (ploty-js)
