### ISSUE TITLE
Add a "map" filter to the knowledge base

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#730]
**Description**
Since complex maps are hard to implement within Taipy, it would be useful to be able to filter out which demos have maps in them to take a look at the code

**Expected change**
Add a map filter [here](https://docs.taipy.io/en/develop/knowledge_base/)
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/b9a09482-02ec-44a5-84b9-cd33f1ac2b2c)

(I would do it but I am unfamiliar with the language, where is this filtering feature implemented?)

**Comment by jrobinAV** [comment]
Ticket https://github.com/Avaiga/taipy-doc/issues/692 is about deciding the filters to add.
