### ISSUE TITLE
BUG-Error setting up documentation (taipy-auth not found)

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-doc#741]
**Bug description**
Followed the instructions in [taipy-doc/INSTALLATION.md](https://github.com/Avaiga/taipy-doc/blob/53e1b0b70f9fa758e4588404230888c4205ad6ce/INSTALLATION.md) to setup the documentation but getting the following error when running `python tools/fetch_source_files.py develop`:

Traceback:
```
Traceback (most recent call last):
  File "/home/arcanaxion/programming/taipy-projects/taipy-dev/taipy-doc/tools/fetch_source_files.py", line 99, in <module>
    raise SystemError(f"Problem with {repo}:\nOutput: {cmd.stdout}\nError: {cmd.stderr}")
SystemError: Problem with taipy-auth:
Output: 
Error: remote: Repository not found.
fatal: repository 'https://github.com/Avaiga/taipy-auth.git/' not found
```

**Expected change**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots better help show the problem.

**Comment by FabienLelaquais** [comment]
The fix was done in the 'develop' branch for Taipy 3.1.
If you *really* need that for 3.0, please let us know!
