### ISSUE TITLE
Taipy Studio is almost non-existent in the doc

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-doc#744]
**Description**
Taipy Studio is not mentioned until the Scenario Management tutorial which comes quite late in the learning journey of Taipy. We should probably add a comment with an image at the beginning of the GUI tutorial so that new users get at least the completion capabilities of Taipy Studio.

**Expected change**
In the beginning of the GUI tutorial. Add a sentence like "If you have VSCode, you can install Taipy Studio, our VSCode extension that provides completions for Taipy code and allows you to edit data pipelines in a graph based editor"
With an image like:
![image](https://github.com/Avaiga/taipy-doc/assets/62465003/d60ff25d-5b14-4a51-b618-7d087fe8213a)

**Comment by Satoshi-Sh** [comment]
I want to take on this issue. There is a description of Taipy Studio [here](https://docs.taipy.io/en/latest/tutorials/fundamentals/1_understanding_gui/#:~:text=this%20notebook.-,Taipy%20Studio,So%2C%20without%20further%20delay%2C%20let%27s%20begin%20to%20code!,-Steps) already.

Maybe I can add a GIF to the section?
![taipy-studio-demo](https://github.com/Avaiga/taipy-doc/assets/73622805/9966682e-d40f-4bb1-8998-bda887e71fc1)

**Comment by FlorianJacta** [comment]
Why not! Having a GIF is more visual. Taipy Studio is useful for the Taipy GUI when using Markdown (not the Python API). It may be better not to explain this.

**Comment by jrobinAV** [comment]
A pull request attached to the issue is currently in review. I am removing the "waiting for contributor" label.
