### ISSUE TITLE
Add Page Builder example in all visual element documentation pages

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-doc#755]
**Description**

Since the Page Builder was introduced, the only available documentation is the global presentation, which is very generic.
The 'code' snippets provided in the elements doc should have an additional section, beside Markdown and HTML.

**Expected change**

A new tab called 'Page Builder' is available for users to copy and paste the relevant code.

**Comment by AlexandreSajus** [comment]
Similar to https://github.com/Avaiga/taipy/issues/526
