### ISSUE TITLE
BUG- Syntax Error  -   Cycles and Scopes  

### ISSUE THREAD

**Issue by Forchapeatl** [Avaiga/taipy-doc#766]
**Bug description**

From[ this tutorial](https://docs.taipy.io/en/latest/knowledge_base/tutorials/cycles_scopes/) we are given the functions to get  all the scenarios in the Cycle and get  the primary scenario of the Cycle with the functions `tp.get_scenarios(cycle=<Cycle>)` and `tp.get_primary(<Cycle>)` respectively.  The code on the tutorial produces a syntax error.  

Even after importing the Cycle library

```py
from taipy.core import   Cycle
```
I can't seem to get the `id` of the Cycle.   I am using the same code on the [tutorial ](https://docs.taipy.io/en/latest/knowledge_base/tutorials/cycles_scopes/).       @trgiangdo  , @jrobinAV  please help me  clarify this issue,  I am not very clear on how to use these functions :  _`tp.get_primary(<Cycle>)` and  `tp.get_scenarios(cycle=<Cycle>)`_ .

**Screenshots**

![image](https://github.com/Avaiga/taipy-doc/assets/24577149/05ae3df6-6d43-4f69-803d-d2a15fc18a3a)

**Comment by trgiangdo** [comment]
The `<Cycle>` here must be a cycle entity.

Please take a look at the document page on https://docs.taipy.io/en/latest/manuals/core/entities/scenario-cycle-mgt/#cycle-attributes to see when a cycle entity is created and how to get one.
