### ISSUE TITLE
KnowledgeBase - Improve left navigation panel for Tips&Tricks

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#803]
**Description**
When https://github.com/Avaiga/taipy-doc/issues/801 is done, we will have many tips in this Tips&Tricks section. The navbar will not be useful anymore.

**Comment by jrobinAV** [comment]
I propose to remove the items from the nav bar, but not he nav bar itself. What do you think?

**Comment by FlorianJacta** [comment]
This is what this issue is about @jrobinAV 

However, I would prefer to add themes to these Tips&Tricks:

- Scenarios Management
        - Scenarios
        - Scenario Comparison
        - Scenario Subscription
        - Data Nodes
        - Skippable Tasks
        - Cycles and Scopes
        - Job Execution mode
        - Manage application versions
- Visuals
        - Callbacks in Taipy
        - Using Tables
         - Multipage application
        - Long Running Callbacks
        - Real-time data visualization
        - Stylekit
- Integration:
        - Integrating Databricks
        - Integrate Third-Party Components
        - Taipy Application on Colab with Ngrok
        - Jupyter Notebooks
- Big Data
        - Using PySpark for Big Data
        - Charts for Big Data
        - Big data models vs. Computer memory
- Deployment
        - Taipy Cloud
