### ISSUE TITLE
Document Python 3.12 support

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#807]
Taipy documentation (the `develop` version) should now say that Taipy supports `Python3.12` as well.

**Comment by Prithviraj676** [comment]
sorry, but just want to clarify, is [this](https://github.com/Avaiga/taipy-doc/blob/ec4d10355b4395fbfc893ee448245e2dbb5e40e1/docs/installation/index.md?plain=1#L13C49-L13C83) the documentation where the supported Python version needs to be updated?
