### ISSUE TITLE
Update deployment documentation

### ISSUE THREAD

**Issue by florian-vuillemot** [Avaiga/taipy-doc#810]
**Description**
Deployment documentation must be updated.
- [ ] Ubuntu
- [ ] Centos
- [ ] Windows
- [ ] Taipy-Cloud
- [ ] Azure
- [ ] Apache

**Expected change**
The documentation must be updated and the taipy-cloud doc must be created.

**Comment by jrobinAV** [comment]
Create an epic for this ticket and split it into multiple issues.

**Comment by florian-vuillemot** [comment]
Split in:
https://github.com/Avaiga/taipy-doc/issues/817
https://github.com/Avaiga/taipy-doc/issues/816
https://github.com/Avaiga/taipy-doc/issues/815
https://github.com/Avaiga/taipy-doc/issues/814
