### ISSUE TITLE
Update deployment documentation

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-doc#813]
The deployment documentation must be updated and some must be created.

- [ ] Ubuntu
- [ ] Centos
- [ ] Windows
- [ ] Taipy-Cloud
- [ ] Azure
- [ ] Apache
- [ ] Docker

**Comment by florian-vuillemot** [comment]
Issue split:
- [Ubuntu + Ubuntu and Apache](https://github.com/Avaiga/taipy-doc/issues/814)
- [Centos + Centos and Apache](https://github.com/Avaiga/taipy-doc/issues/815)
- [Docker](https://github.com/Avaiga/taipy-doc/issues/781)
- [Taipy Cloud](https://github.com/Avaiga/taipy-doc/issues/816)
- [Windows](https://github.com/Avaiga/taipy-doc/issues/817)

**Comment by jrobinAV** [comment]
> Issue split:
> 
> * [Ubuntu + Ubuntu and Apache](https://github.com/Avaiga/taipy-doc/issues/814)
> * [Centos + Centos and Apache](https://github.com/Avaiga/taipy-doc/issues/815)
> * [Docker](https://github.com/Avaiga/taipy-doc/issues/781)
> * [Taipy Cloud](https://github.com/Avaiga/taipy-doc/issues/816)
> * [Windows](https://github.com/Avaiga/taipy-doc/issues/817)

Awesome. Thx!
