### ISSUE TITLE
Better space management in doc

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#897]
**Description**
When the page contains no titles and subtitles, TOC (the blank area in orange here) should be disabled to let content (the area in red) expand to the right.

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/c07b2436-bb67-4157-9a41-5187598d78a6)

**Comment by Satoshi-Sh** [comment]
I want to take this issue. 

I have a question. It's working fine on the production, but on the development, I see some errors in `manuals/auth/authentication.md`, `manuals/auth/authorization.md`, `manuals/auth/aindex.md`. Is it only on my end?

![Screenshot from 2024-05-30 21-22-05](https://github.com/Avaiga/taipy-doc/assets/73622805/4b0891fb-7caa-4c10-843c-54ccfd6bde03)

**Comment by FlorianJacta** [comment]
I am assigning you to the issue. I don't understand your problem here. Let me ping @FabienLelaquais

**Comment by FlorianJacta** [comment]
The PR is blocked; the contributor worked on this issue

**Comment by FlorianJacta** [comment]
The PR is blocked; there is a contributor assigned
