### ISSUE TITLE
Add colors to cards

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#899]
**Description**

I would give these cards a more colored look, like the ones we have in the Tutorials to make them pop a little more and ensure consistency.

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/5a874dab-37d0-41e3-8e2d-b7baa66a90f3)

**Comment by Satoshi-Sh** [comment]
Can I take this task?

**Comment by FlorianJacta** [comment]
These cards have changed. It might not be useful anymore.

**Comment by Satoshi-Sh** [comment]
I can find those cards [here](https://docs.taipy.io/en/latest/manuals/usermans/) 
Let me know if you like an updated version, and I can make a pull request.

## Current 
![Screenshot from 2024-05-13 08-09-52](https://github.com/Avaiga/taipy-doc/assets/73622805/157face5-c982-46e2-9456-3efb06c2dfce)
## Updated 
![Screenshot from 2024-05-13 08-22-24](https://github.com/Avaiga/taipy-doc/assets/73622805/986d4783-1409-4ef7-8c31-28a54e58bd64)

**Comment by FlorianJacta** [comment]
Oh, great! You could change the yellow to purple or have the same order of color as the Gallery and delete the "Read More". Nevertheless, I will assign this issue to you!
