### ISSUE TITLE
Documentation - Organize the backend documentation onto 3 main topics

### ISSUE THREAD

**Issue by AAstridVH** [Avaiga/taipy-doc#9]
**Description**
Those topics may be:

- Data collection
- Scenario management
- DevOps ("Going live": deploy the solution)

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by jrobinAV** [comment]
Obsolete
