### ISSUE TITLE
BUG Project Installation

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy-doc#944]
**Bug description**
I was trying to run the doc locally by following the `installation.md`.

 The first step `python tools/fetch_source_files.py develop` gives an error as the screenshot shows.  

>  python tools/fetch_source_files.py develop
Traceback (most recent call last):
  File "/home/satoshi/projects/taipy-doc/tools/fetch_source_files.py", line 99, in <module>
    raise SystemError(f"Problem with {repo}:\nOutput: {cmd.stdout}\nError: {cmd.stderr}")
SystemError: Problem with taipy-enterprise:
Output: 
Error: remote: Repository not found.
fatal: repository 'https://github.com/Avaiga/taipy-enterprise.git/' not found

**Screenshots**
![Screenshot from 2024-05-06 08-35-25](https://github.com/Avaiga/taipy-doc/assets/73622805/c5f1fe10-7cde-4202-a2c1-6dbe74403308)

**Comment by FlorianJacta** [comment]
@Satoshi-Sh You should now be able to contribute to our documentation. We have fixed the issue. Thank you for creating it!

**Comment by Satoshi-Sh** [comment]
Thanks for the help, @FabienLelaquais . 

I have another issue in step 3. When I ran the `mkdocs serveError`, I got an error message "Config file 'mkdocs.yml' does not exist." Should I make a mkdocs.yml from the `mkdocs.yml_template`?

I tried that way but the template file has a syntax issue on the lines 186 and 187.
![Screenshot from 2024-05-07 08-10-21](https://github.com/Avaiga/taipy-doc/assets/73622805/72b6c66e-6411-4ea3-9c74-ca7ae041c112)

The documentation ran fine after I added indents to [REFERENCE_CONTENT] and [REFERENCE_CONTENT]. I'm not sure if I'm doing right. It would be great if you could have a look at this.

**Comment by FabienLelaquais** [comment]
My pleasure, @Satoshi-Sh 
The mkdocs.yml file is generated by the `tools/setup_generation.py` script, after `fetch_source_files` was run.

That is described in `INSTALLATION.md`, step 2.

Please let us know what gives.

**Comment by Satoshi-Sh** [comment]
Thanks. You were right. The terminal didn't run `pipenv run python tools/setup_generation.py`.  It's working fine now.
