### ISSUE TITLE
BUG TypeError in filter.js

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy-doc#950]
**Bug description**
There is a TypeError in the browser console. 
**Expected change**
The browser console doesn't show the error message. (Just need to add if statement for document.getElementById('filter-all'))

**Screenshots**
![Screenshot from 2024-05-07 11-32-50](https://github.com/Avaiga/taipy-doc/assets/73622805/1c26a3ce-b569-4554-8dd3-cde8f8f91211)

**Comment by trgiangdo** [comment]
Hello @Satoshi-Sh, thank you for reporting the issue and propose a PR to fix it. We will look into the PR as soon as the holidays over by next week. Thank you
