### ISSUE TITLE
Missing viselement/index.md 

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy-doc#953]
**Bug description**
Visual Elements card link redirects to `viselement/index.md` but the file doesn't exist in the project and gives a 404 error. 

**Expected change**
Display the right content.

**Screenshots**
![link-not-working](https://github.com/Avaiga/taipy-doc/assets/73622805/d42ff32a-f2a8-4b0b-9646-7eb1e86b0a53)

**Comment by trgiangdo** [comment]
Hello @Satoshi-Sh, thank you for the bug report. We will fix this asap
