### ISSUE TITLE
BUG-Erase td in CSS in table styling doc

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#965]
**Bug description**
Related to: https://github.com/Avaiga/taipy/issues/1279

Page to change: https://docs.taipy.io/en/latest/manuals/gui/viselements/table/#styling-rows

The documentation is not correct. Styling like that doesn't work.

**Expected change**
The *td* should be erased from the doc.

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by FlorianJacta** [comment]
Sure!

**Comment by FlorianJacta** [comment]
A PR is in progress
