### ISSUE TITLE
Hunt usages of legacy Taipy visuals

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-doc#972]
**Description**

The Taipy icon was changed in april 2024.
We want to ensure the new logo and icon are used were needed.

This includes all manuals (including visual element images and Taipy Studio animations).

**Expected change**
 
The new logo, tag line and icon are used where appropriate.

**Comment by jrobinAV** [comment]
@FabienLelaquais I believe this is done. Am I wrong?

**Comment by FabienLelaquais** [comment]
Hunting is a life-long necessity.
However, let me check and close if needed.
Thanks

**Comment by jrobinAV** [comment]
🏹🐗
