### ISSUE TITLE
Support the hiding of element properties using viselements.json

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-doc#977]
**Description**
That would allow to hide a property from any element's documentation.

**Proposed solution**

The best place to indicate that a given property, for a given element, should be hidden, is the `viselements.json` file where it is declared.
This file is used for generating the documentation, for the auto-completion feature of Visual Studio GUI, and the generation of the Page Builder API.

*Non inherited property*
In order to hide an element's property, we propose to simply prefix the documentation content with the string "UNDOCUMENTED".

*Inherited property*
Inherited properties (such as `id` or `hover_text`) cannot use this mechanism because the element property's doc attributes are merged.

We propose to add an attribute called `hide` in the JSON description.
`hide` would be of type `boolean` and default to `false`.

**Expected change**
```
                    {
                        "name": "hover_text",
                        "type": "dynamic(str)",
                        "doc": "The information that is displayed when the user hovers over this element."
                    }
```
would be declared in `indicator` (who inherit from `shared`) as 
```
                    {
                        "name": "hover_text",
                        "hide": true
                    }

```

**Comment by Satoshi-Sh** [comment]
I'm interested in this issue. 

My first thought is to add the condition statement 
```
if property_desc.get('hide'):
   continue
```
to lines 248-249 in the `tools/setup_generation/step_viselments.py` . Does this look fine?

I don't know how to test this update.

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais what do you think ?

**Comment by FabienLelaquais** [comment]
@Satoshi-Sh the problem is slightly more complex than that because of the inheritance issue.
Enjoy the PR that comes in a few minutes to see how I did the trick.
