### ISSUE TITLE
Add description for fullwidth property in file_selector and file_download

### ISSUE THREAD

**Issue by Satoshi-Sh** [Avaiga/taipy-doc#981]
**Description**
As fullwidth is implemented for file_selector and file_download in [taipy/#1345](https://github.com/Avaiga/taipy/pull/1345#event-13046181646), we need to add the description to those pages.

**Example**
Here is the example from the date page. 
![Screenshot from 2024-06-05 06-07-53](https://github.com/Avaiga/taipy-doc/assets/73622805/ed6972b4-744f-458a-bd3d-233971eb5a65)

**Comment by Satoshi-Sh** [comment]
Can I take on this issue?

**Comment by FlorianJacta** [comment]
Sure, you can!

**Comment by FlorianJacta** [comment]
Blocked by https://github.com/Avaiga/taipy-doc/pull/940

**Comment by jrobinAV** [comment]
> Blocked by [#940](https://github.com/Avaiga/taipy-doc/pull/940)

It is now unblocked.
